@startuml
'https://plantuml.com/class-diagram

'___________STYLES___________
title UML - ATM
skinparam classAttributeIconSize 0
skinparam backgroundColor White
skinparam RoundCorner 10
skinparam Shadowing true

skinparam class {
    ArrowColor Black
    BackgroundColor White
    HeaderBackgroundColor Gray
    BorderColor Black
    FontColor White
    FontSize 14
    AttributeFontSize 12
}

skinparam object{
    ArrowColor Black
    BackgroundColor White
    BorderColor Black
    FontColor Black
    FontSize 14
    AttributeFontSize 12
}

skinparam note {
    BackgroundColor LightYellow
    BorderColor Black
}

'___________UML___________

interface IServiceATM{
+procesarRetiro(dni: String, contraseña: String, montoARetirar: Integer)
}

class ServiceATM{
-autenticationService: AutenticationService
-cuentaService: CuentaService
-cajaService: CajaService
+ServiceATM(autenticationService: AutenticationService, cuentaService: CuentaService, cajaService: CajaService)
+procesarRetiro(dni: String, contraseña: String, montoARetirar: Integer)
}

class AutenticationService{
+validarUsuarioYContraseña(dni, contraseña): Boolean
}

class CuentaService{
+getCuenta(dni: String): Cuenta
}

class CajaService{
+entregarDinero(c: Cuenta, Integer montoARetirar)
}

class Cuenta{
-dni: String
-saldoActual: Integer
+Cuenta(String dni, Integer saldoActual)
+getDNI(): String
+setDNI()
+getSaldoActual(): integer
+setSaldoActual()
}

class DineroATM{
-dineroDisponible: Integer
-getDineroDisponible(): Integer
-setDineroDisponible()
-recargarDineroATM(dineroRecarga: Integer)
}

class AutenticationDatabase{
-dni: String
-contraseña: String
+AutenticationService(dni: String, contraseña: String)
+getDNI(): String
+setDNI()
+getContraseña(): String
+setContraseña()
}

object appCliente{
}

IServiceATM<|..ServiceATM
ServiceATM --> AutenticationService
ServiceATM --> CuentaService
ServiceATM --> CajaService
appCliente.>IServiceATM
CajaService..>DineroATM
CuentaService..>Cuenta
AutenticationService..>AutenticationDatabase

@enduml